from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))

from pointneuron.data.swc import SwcNode, parse_swc, write_swc


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate an SWC tree from a PointNeuron graph .npz.")
    parser.add_argument("--graph", required=True, help="Graph .npz with centers, radii, scores, and edges.")
    parser.add_argument("--root-mode", default="endpoint_radius", choices=["endpoint_radius", "endpoint_score", "radius", "score", "first"], help="Root selection heuristic.")
    parser.add_argument("--output", default="tmp/reconstructions/reconstruction.swc", help="Output SWC path.")
    parser.add_argument("--compare-swc", help="Optional GT SWC used only to report nearest-node distances.")
    args = parser.parse_args()

    graph_path = Path(args.graph)
    graph = np.load(graph_path, allow_pickle=False)
    centers = graph["centers"].astype(np.float32, copy=False)
    radii = graph["radii"].astype(np.float32, copy=False) if "radii" in graph else np.ones((centers.shape[0],), dtype=np.float32)
    scores = graph["scores"].astype(np.float32, copy=False) if "scores" in graph else np.ones((centers.shape[0],), dtype=np.float32)
    edges = graph["edges"].astype(np.int64, copy=False) if "edges" in graph else np.zeros((0, 2), dtype=np.int64)
    edge_paths = load_edge_paths(graph, edges)
    metadata = json.loads(str(graph["metadata"])) if "metadata" in graph else {}

    if centers.shape[0] == 0:
        print("Graph has no nodes; refusing to write an empty SWC.")
        return 2

    roots = choose_component_roots(centers, radii, scores, edges, args.root_mode)
    nodes = graph_to_swc_nodes(centers, radii, scores, edges, roots, edge_paths=edge_paths)
    write_swc(
        args.output,
        nodes,
        comments=[
            "Generated by PointNeuron graph-to-SWC interpreter.",
            f"source_graph: {graph_path}",
            f"root_mode: {args.root_mode}",
            f"source_metadata: {json.dumps(metadata, separators=(',', ':'))[:800]}",
        ],
    )

    parsed = parse_swc(args.output)
    errors = parsed.validate()
    if errors:
        print(f"Generated invalid SWC: {args.output}")
        for error in errors:
            print(f"  {error}")
        return 2

    print(f"nodes: {len(parsed.nodes)}")
    print(f"edges: {parsed.edge_count}")
    print(f"roots: {parsed.root_count}")
    print(f"components: {len(roots)}")
    print(f"root_indices: {','.join(str(root) for root in roots)}")
    if args.compare_swc:
        report_distances(centers, args.compare_swc)
    print(f"output: {args.output}")
    return 0


def choose_component_roots(
    centers: np.ndarray,
    radii: np.ndarray,
    scores: np.ndarray,
    edges: np.ndarray,
    root_mode: str,
) -> list[int]:
    adjacency = adjacency_lists(centers.shape[0], edges)
    components = connected_components(adjacency)
    roots = []
    for component in components:
        component_array = np.array(component, dtype=np.int64)
        degrees = np.array([len(adjacency[index]) for index in component], dtype=np.int64)
        endpoints = component_array[degrees <= 1]
        candidates = endpoints if endpoints.size else component_array
        if root_mode == "endpoint_radius":
            root = int(candidates[np.argmax(radii[candidates])])
        elif root_mode == "endpoint_score":
            root = int(candidates[np.argmax(scores[candidates])])
        elif root_mode == "radius":
            root = int(component_array[np.argmax(radii[component_array])])
        elif root_mode == "score":
            root = int(component_array[np.argmax(scores[component_array])])
        else:
            root = int(component_array[0])
        roots.append(root)
    return roots


def graph_to_swc_nodes(
    centers: np.ndarray,
    radii: np.ndarray,
    scores: np.ndarray,
    edges: np.ndarray,
    roots: list[int],
    edge_paths: dict[tuple[int, int], np.ndarray] | None = None,
) -> list[SwcNode]:
    adjacency = adjacency_lists(centers.shape[0], edges)
    original_to_swc_id: dict[int, int] = {}
    nodes: list[SwcNode] = []
    next_id = 1
    for root in roots:
        if root in original_to_swc_id:
            continue
        original_to_swc_id[root] = next_id
        x, y, z = centers[root].tolist()
        nodes.append(
            SwcNode(
                node_id=next_id,
                node_type=3,
                x=float(x),
                y=float(y),
                z=float(z),
                radius=float(max(radii[root], 1.0e-3)),
                parent_id=-1,
            )
        )
        next_id += 1
        queue = [root]
        while queue:
            parent = queue.pop(0)
            neighbors = [neighbor for neighbor in adjacency[parent] if neighbor not in original_to_swc_id]
            neighbors.sort(key=lambda neighbor: (-float(scores[neighbor]), float(np.linalg.norm(centers[parent] - centers[neighbor]))))
            for neighbor in neighbors:
                parent_swc_id = original_to_swc_id[parent]
                path = oriented_edge_path(edge_paths, parent, neighbor)
                if path is None:
                    path = np.stack([centers[parent], centers[neighbor]], axis=0)
                if path.shape[0] <= 1:
                    path = np.stack([centers[parent], centers[neighbor]], axis=0)
                previous_id = parent_swc_id
                for point_index, point in enumerate(path[1:], 1):
                    fraction = point_index / max(path.shape[0] - 1, 1)
                    radius = float((1.0 - fraction) * radii[parent] + fraction * radii[neighbor])
                    nodes.append(
                        SwcNode(
                            node_id=next_id,
                            node_type=3,
                            x=float(point[0]),
                            y=float(point[1]),
                            z=float(point[2]),
                            radius=float(max(radius, 1.0e-3)),
                            parent_id=int(previous_id),
                        )
                    )
                    previous_id = next_id
                    next_id += 1
                original_to_swc_id[neighbor] = previous_id
                queue.append(neighbor)

    return nodes


def load_edge_paths(graph, edges: np.ndarray) -> dict[tuple[int, int], np.ndarray] | None:
    if "edge_path_points" not in graph or "edge_path_offsets" not in graph:
        return None
    points = graph["edge_path_points"].astype(np.float32, copy=False)
    offsets = graph["edge_path_offsets"].astype(np.int64, copy=False)
    if offsets.shape[0] != edges.shape[0] + 1:
        raise ValueError("edge_path_offsets must have one more entry than edges")
    paths: dict[tuple[int, int], np.ndarray] = {}
    for edge_index, (left, right) in enumerate(edges.tolist()):
        start = int(offsets[edge_index])
        end = int(offsets[edge_index + 1])
        paths[tuple(sorted((int(left), int(right))))] = points[start:end]
    return paths


def oriented_edge_path(edge_paths: dict[tuple[int, int], np.ndarray] | None, parent: int, neighbor: int) -> np.ndarray | None:
    if edge_paths is None:
        return None
    key = tuple(sorted((int(parent), int(neighbor))))
    path = edge_paths.get(key)
    if path is None:
        return None
    if parent <= neighbor:
        return path
    return path[::-1]


def adjacency_lists(node_count: int, edges: np.ndarray) -> list[list[int]]:
    adjacency: list[list[int]] = [[] for _ in range(node_count)]
    for left, right in edges.tolist():
        left = int(left)
        right = int(right)
        if left == right or left < 0 or right < 0 or left >= node_count or right >= node_count:
            continue
        adjacency[left].append(right)
        adjacency[right].append(left)
    return adjacency


def connected_components(adjacency: list[list[int]]) -> list[list[int]]:
    seen = set()
    components = []
    for start in range(len(adjacency)):
        if start in seen:
            continue
        component = []
        stack = [start]
        seen.add(start)
        while stack:
            node = stack.pop()
            component.append(node)
            for neighbor in adjacency[node]:
                if neighbor not in seen:
                    seen.add(neighbor)
                    stack.append(neighbor)
        components.append(sorted(component))
    return components


def report_distances(centers: np.ndarray, swc_path: str) -> None:
    swc = parse_swc(swc_path)
    gt = np.array([[node.x, node.y, node.z] for node in swc.nodes], dtype=np.float32)
    if gt.size == 0:
        return
    distances = []
    for start in range(0, centers.shape[0], 512):
        chunk = centers[start : start + 512]
        distances.append(np.linalg.norm(chunk[:, None, :] - gt[None, :, :], axis=2).min(axis=1))
    nearest = np.concatenate(distances)
    print(f"mean_nearest_gt_distance: {float(nearest.mean()):.4f}")
    print(f"median_nearest_gt_distance: {float(np.median(nearest)):.4f}")


if __name__ == "__main__":
    raise SystemExit(main())
